# Generated by Django 5.1.3 on 2025-12-16 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='date',
        ),
        migrations.AddField(
            model_name='studysession',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 18, 30, 27, 683496)),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress_notes', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
